name: gerencianet
description: A dart library for integration with payment services provided by Gerencianet.
version: 1.1.1
homepage: https://github.com/gerencianet/gn-api-sdk-dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  encrypt: ^5.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.17.1

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: gerencianet
