name: gerencianet
description: A dart library for integration of your backend with the payment services provided by Gerencianet.
version: 1.0.0
homepage: 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.17.1

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: gerencianet
